### ISSUE TITLE
SegmentationTree class is missing

### ISSUE THREAD

**Issue by MansurBib** [kdavila/lecturemath#1]
There are couple references in ACCESS2021_release of SegmentationTree but it's nowhere to be found

**Comment by kdavila** [comment]
Hello,

Can you provide more details on which script where you trying to execute,
and the specific line of code throwing the error?

Thanks,
Kdavila

**Comment by MansurBib** [comment]
in
[ACCESS2021_release/AccessMath/annotation/keyframe_words.py](https://github.com/kdavila/lecturemath/blob/7836868241de4c83f3884c4511a82d7af9e22477/ACCESS2021_release/AccessMath/annotation/keyframe_words.py#L6)
[ACCESS2021_release/AccessMath/annotation/gt_projection_annotator.py](https://github.com/kdavila/lecturemath/blob/7836868241de4c83f3884c4511a82d7af9e22477/ACCESS2021_release/AccessMath/annotation/gt_projection_annotator.py#L760)
[ACCESS2021_release/AccessMath/annotation/gt_word_annotator.py](https://github.com/kdavila/lecturemath/blob/7836868241de4c83f3884c4511a82d7af9e22477/ACCESS2021_release/AccessMath/annotation/gt_word_annotator.py#L20)
[ACCESS2021_release/AccessMath/annotation/gt_unique_word_annotator.py](https://github.com/kdavila/lecturemath/blob/7836868241de4c83f3884c4511a82d7af9e22477/ACCESS2021_release/AccessMath/annotation/gt_unique_word_annotator.py#L26)

there are imports for SegmentationTree like this
```python
from AccessMath.preprocessing.content.segmentation_tree import SegmentationTree
```

but when looking into the path there is not segmentation_tree.py or the class SegmentationTree to be found in the repository

**Comment by kdavila** [comment]
I see. Please note the AccessMath library has been used internally for
multiple projects including some earlier publications and even a few
non-published projects. This repository only contains the minimum set of
classes needed to reproduce the work specifically related to our IEEE
ACCESS paper from 2021 (
https://ieeexplore.ieee.org/abstract/document/9494351). In that paper, we
did not use the word-level annotator, hence we omitted the class. We have a
separate release for the annotation tools:
https://github.com/adaniefei/vid_annotation_tool/tree/main

That said, I just pushed the missing file.

Best,
kdavila

On Tuesday, January 2, 2024, MansurBib ***@***.***> wrote:

> in
>
>
> ACCESS2021_release/AccessMath/annotation/keyframe_words.py
> <https://github.com/kdavila/lecturemath/blob/7836868241de4c83f3884c4511a82d7af9e22477/ACCESS2021_release/AccessMath/annotation/keyframe_words.py#L6>
> ACCESS2021_release/AccessMath/annotation/gt_projection_annotator.py
> <https://github.com/kdavila/lecturemath/blob/7836868241de4c83f3884c4511a82d7af9e22477/ACCESS2021_release/AccessMath/annotation/gt_projection_annotator.py#L760>
> ACCESS2021_release/AccessMath/annotation/gt_word_annotator.py
> <https://github.com/kdavila/lecturemath/blob/7836868241de4c83f3884c4511a82d7af9e22477/ACCESS2021_release/AccessMath/annotation/gt_word_annotator.py#L20>
> ACCESS2021_release/AccessMath/annotation/gt_unique_word_annotator.py
> <https://github.com/kdavila/lecturemath/blob/7836868241de4c83f3884c4511a82d7af9e22477/ACCESS2021_release/AccessMath/annotation/gt_unique_word_annotator.py#L26>
>
>
there are imports for SegmentationTree like this

**Comment by MansurBib** [comment]
Ohhh I understand. Thank you very much and best wishes
